import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Globe from "@/components/ui/globe";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexclerKProvider from "@/providers/convex-clerk-provider";
import { Toaster } from "@/components/ui/sonner";
import { ModalProvider } from "@/providers/modalProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en"> 
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ConvexclerKProvider >
          <ModalProvider/>
         <Toaster/>
        {children}
       
        </ConvexclerKProvider>
      </body>
    </html>
    
  );
}
